#! /bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch_proxy
# Required-Start:    $all
# Required-Stop:    $all
# Default-Start:    2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch_proxy
# Description:      Starts elasticsearch_proxy using hypnotoad
### END INIT INFO
 
ES_HOME=`dirname $0`/../../
SCRIPT=$ES_HOME/scripts/elasticsearch_proxy/elasticsearch_proxy.pl

case $HOSTNAME in
  ('ves-hx-e6.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.igsr.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/igsr_website_staging
    ;;
  ('ves-pg-e6.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.igsr.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/igsr_website
    ;;
  ('ves-oy-e6.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.igsr.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/igsr_website
    ;;
  ('ves-hx-e5.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.hipsci.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/hipsci_portal_staging
    ;;
  ('ves-pg-e5.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.hipsci.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/hipsci_portal
    ;;
  ('ves-oy-e5.ebi.ac.uk')
    MOJO_CONF=$ES_HOME/config/elasticsearchproxy.hipsci.conf
    PROJECT_HOME=/nfs/public/rw/reseq-info/hipsci_portal
    ;;
esac
export MOJO_CONF
export PROJECT_HOME


set -e
 
case "$1" in
  start)
    echo "Starting $SCRIPT"
    cd $ES_HOME
    carton exec hypnotoad $SCRIPT
    ;;
  stop)
    echo "Stopping $SCRIPT"
    cd $ES_HOME
    carton exec hypnotoad --stop $SCRIPT
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
 
exit 0
