#! /bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch
# Required-Start:    $all
# Required-Stop:    $all
# Default-Start:    2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch
# Description:      Starts elasticsearch using start-stop-daemon
### END INIT INFO

case $DATACENTRE in
  ('np2')
    PROJECT_HOME=/nfs/public/rw/igsr/elastic_search_staging/
    ;;
  ('p1m')
    PROJECT_HOME=/nfs/public/rw/igsr/elastic_search_staging/
  *)
    PROJECT_HOME=/nfs/public/rw/igsr/elastic_search
    ;;
esac

ES_HOME=/nfs/public/rw/homes/vg_igsr_adm/elasticsearch/elasticsearch-1.5.1/
ES_HEAP_SIZE=2g
DAEMON=$ES_HOME/bin/elasticsearch
NAME=gca_elasticsearch_${DATACENTRE}
DESC=gca_elasticsearch_${DATACENTRE}
PID_FILE=/mnt/data/var/run/$NAME.pid
LOG_DIR=$PROJECT_HOME/var/log/$HOSTNAME
DATA_DIR=/mnt/data/var/lib/
WORK_DIR=/mnt/data/tmp/$NAME
TEMP_DIR=/mnt/data/tmp/$NAME
CLUSTER_NAME=$NAME
NODE_NAME=$HOSTNAME
CONFIG_FILE=$CONF_DIR/elasticsearch.yml
CONF_DIR=$PROJECT_HOME/gca_elasticsearch/config/
DAEMON_OPTS="-d -p $PID_FILE -Des.config=$CONFIG_FILE -Des.path.conf=$CONF_DIR -Des.path.home=$ES_HOME -Des.path.logs=$LOG_DIR -Des.path.data=$DATA_DIR -Des.path.work=$WORK_DIR -Des.node.name=$NODE_NAME -Des.cluster.name=$CLUSTER_NAME -Djna.tmpdir=$TEMP_DIR"

test -x $DAEMON || exit 0
 
set -e
 
case "$1" in
  start)
    echo "Starting $DESC"
    mkdir -p $LOG_DIR $DATA_DIR $WORK_DIR
    export ES_HEAP_SIZE
    $DAEMON $DAEMON_OPTS
    ;;
  stop)
    [ -f $PID_FILE ] || exit
    echo "Stopping $DESC"
    kill -9 `cat $PID_FILE`
    rm -f $PID_FILE
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
 
exit 0
