#! /bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch_proxy
# Required-Start:    $all
# Required-Stop:    $all
# Default-Start:    2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch_proxy
# Description:      Starts elasticsearch_proxy using hypnotoad
### END INIT INFO
 
ES_HOME=`dirname $0`/../../
SCRIPT=$ES_HOME/scripts/elasticsearch_proxy/elasticsearch_proxy.pl

set -e
 
case "$1" in
  start)
    echo "Starting $SCRIPT"
    cd $ES_HOME
    carton exec hypnotoad $SCRIPT
    ;;
  stop)
    echo "Stopping $SCRIPT"
    carton exec hypnotoad --stop $SCRIPT
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
 
exit 0
